version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: Austin
  coins:
  - 10000token
  - 100000000stake
  mnemonic: swamp hen mercy tiger gas peanut minor affair plug oven trigger review
    present black typical remain marine social dragon crumble cluster dream cereal
    primary
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  hooks:
    path: react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
